### ISSUE TITLE
获取ResourceBundle失败

### ISSUE THREAD

**Issue by lispwu** [Aresyi/HowTomcatWorks#2]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.catalina.connector.http.HttpConnector.createRequest(HttpConnector.java:740)
	at org.apache.catalina.connector.http.HttpProcessor.<init>(HttpProcessor.java:76)
	at org.apache.catalina.connector.http.HttpConnector.newProcessor(HttpConnector.java:864)
	at org.apache.catalina.connector.http.HttpConnector.start(HttpConnector.java:1164)
	at ex07.pyrmont.startup.Bootstrap.main(Bootstrap.java:62)
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.apache.catalina.connector.LocalStrings, locale zh_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.apache.catalina.util.StringManager.<init>(StringManager.java:107)
	at org.apache.catalina.util.StringManager.getManager(StringManager.java:252)
	at org.apache.catalina.connector.RequestBase.<clinit>(RequestBase.java:185)
	... 5 more

**Comment by lispwu** [comment]
运行的时候报这个错

**Comment by Aresyi** [comment]
看看是不是所缺的依赖包在lib目录下面

**Comment by GreedyWalf** [comment]
我测试了第一个例子，响应index.html时，代码中没有设置响应头信息，直接读取index.html文件流，响应到浏览器上，会造成html内容无法渲染，加上Response的Content-Type Content-Length等信息，才可以正常请求index.html，请问楼主不知道是不是这样的。。

**Comment by SuHuo** [comment]
> 我测试了第一个例子，响应index.html时，代码中没有设置响应头信息，直接读取index.html文件流，响应到浏览器上，会造成html内容无法渲染，加上Response的Content-Type Content-Length等信息，才可以正常请求index.html，请问楼主不知道是不是这样的。。

我测试也是这样，没有响应头的话浏览器解析不了html。Servlet那个例子也是，没有响应头的话，浏览器不能解析servlet里输出的内容

**Comment by xch900910** [comment]
> > 我测试了第一个例子，响应index.html时，代码中没有设置响应头信息，直接读取index.html文件流，响应到浏览器上，会造成html内容无法渲染，加上Response的Content-Type Content-Length等信息，才可以正常请求index.html，请问楼主不知道是不是这样的。。
> 
> 我测试也是这样，没有响应头的话浏览器解析不了html。Servlet那个例子也是，没有响应头的话，浏览器不能解析servlet里输出的内容

是的，我的也是要加响应头浏览器才渲染html，但是img标签的内容加上也显示不了
![Uploading image.png…]()
